"""schema inicial

Revision ID: 41ff899e9872
Revises: 0001
Create Date: 2026-08-07 19:42:33.558557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '41ff899e9872'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_boards_slug'), 'boards', ['slug'], unique=True)
    op.create_table('exams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_year'), 'exams', ['year'], unique=False)
    op.create_table('states',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_uf'), 'states', ['uf'], unique=True)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_total_xp'), 'users', ['total_xp'], unique=False)
    op.create_table('questions',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.String(length=4), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_level_enum'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_board_id'), 'questions', ['board_id'], unique=False)
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=True)
    op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_index('ix_questions_filter_composite', 'questions', ['board_id', 'subject_id', 'year', 'difficulty_level', 'state_id'], unique=False)
    op.create_index(op.f('ix_questions_state_id'), 'questions', ['state_id'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questions_year'), 'questions', ['year'], unique=False)
    op.create_table('notebook_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'REVIEWED', 'MASTERED', name='notebook_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_items_question_id'), 'notebook_items', ['question_id'], unique=False)
    op.create_index(op.f('ix_notebook_items_status'), 'notebook_items', ['status'], unique=False)
    op.create_index(op.f('ix_notebook_items_user_id'), 'notebook_items', ['user_id'], unique=False)
    op.create_index('ux_notebook_user_question', 'notebook_items', ['user_id', 'question_id'], unique=True)
    op.create_table('student_comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_question_approved', 'student_comments', ['question_id', 'is_approved'], unique=False)
    op.create_index(op.f('ix_student_comments_question_id'), 'student_comments', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_comments_user_id'), 'student_comments', ['user_id'], unique=False)
    op.create_table('user_answers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=4), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_cebraspe_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index('ix_user_answers_user_created', 'user_answers', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    op.create_table('comment_reports',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['student_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_comment_reports_comment_user', 'comment_reports', ['comment_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_comment_reports_comment_user', table_name='comment_reports')
    op.drop_table('comment_reports')
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index('ix_user_answers_user_created', table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_student_comments_user_id'), table_name='student_comments')
    op.drop_index(op.f('ix_student_comments_question_id'), table_name='student_comments')
    op.drop_index('ix_comments_question_approved', table_name='student_comments')
    op.drop_table('student_comments')
    op.drop_index('ux_notebook_user_question', table_name='notebook_items')
    op.drop_index(op.f('ix_notebook_items_user_id'), table_name='notebook_items')
    op.drop_index(op.f('ix_notebook_items_status'), table_name='notebook_items')
    op.drop_index(op.f('ix_notebook_items_question_id'), table_name='notebook_items')
    op.drop_table('notebook_items')
    op.drop_index(op.f('ix_questions_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_state_id'), table_name='questions')
    op.drop_index('ix_questions_filter_composite', table_name='questions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_index(op.f('ix_questions_board_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_total_xp'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_states_uf'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_exams_year'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_boards_slug'), table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###
